// AUTO-GENERATED by tools/gen-seed.mjs — do not edit by hand.
export const SEED = [
  {
    "id": "r001",
    "name": "Le Nile Bleu",
    "cuisine": "Ethiopian",
    "city": "Montreal",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 2,
        "p": 0.5
      }
    ],
    "sort": 1
  },
  {
    "id": "r002",
    "name": "Picks",
    "cuisine": "Canadian & Comfort",
    "city": "Montreal",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 9,
        "p": 9
      }
    ],
    "sort": 2
  },
  {
    "id": "r003",
    "name": "Bistro Tôt ou Tard",
    "cuisine": "French",
    "city": "Montreal",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 8.25,
        "p": 8.25
      }
    ],
    "sort": 3
  },
  {
    "id": "r004",
    "name": "Kagayaki",
    "cuisine": "Japanese",
    "city": "Montreal",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 9,
        "p": 9.75
      }
    ],
    "sort": 4
  },
  {
    "id": "r005",
    "name": "Sushi Momo",
    "cuisine": "Japanese",
    "city": "Montreal",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 9.25,
        "p": 9.25
      }
    ],
    "sort": 5
  },
  {
    "id": "r006",
    "name": "Tacos Tin Tan",
    "cuisine": "Mexican",
    "city": "Montreal",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 8.25,
        "p": 7.75
      }
    ],
    "sort": 6
  },
  {
    "id": "r007",
    "name": "Le P'tit Rustik",
    "cuisine": "French",
    "city": "Montreal",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 8.75,
        "p": 8.25
      },
      {
        "label": "2025",
        "k": 7.5,
        "p": 7.5
      }
    ],
    "sort": 7
  },
  {
    "id": "r008",
    "name": "Pho Nguyen",
    "cuisine": "Vietnamese",
    "city": "Montreal",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 8,
        "p": 8
      }
    ],
    "sort": 8
  },
  {
    "id": "r009",
    "name": "Dandy",
    "cuisine": "Brunch",
    "city": "Montreal",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 9.25,
        "p": 9
      }
    ],
    "sort": 9
  },
  {
    "id": "r010",
    "name": "Le Toaster",
    "cuisine": "Brunch",
    "city": "Montreal",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 8.75,
        "p": 8.5
      }
    ],
    "sort": 10
  },
  {
    "id": "r011",
    "name": "Le Mekong",
    "cuisine": "Vietnamese",
    "city": "Montreal",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 7,
        "p": 6.75
      }
    ],
    "sort": 11
  },
  {
    "id": "r012",
    "name": "Muru Crêpes",
    "cuisine": "Brunch",
    "city": "Montreal",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 9,
        "p": 8
      }
    ],
    "sort": 12
  },
  {
    "id": "r013",
    "name": "India Rosa Griffintown",
    "cuisine": "Indian",
    "city": "Montreal",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 7,
        "p": 5
      }
    ],
    "sort": 13
  },
  {
    "id": "r014",
    "name": "L'Gros Luxe",
    "cuisine": "Canadian & Comfort",
    "city": "Montreal",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 5,
        "p": 4
      }
    ],
    "sort": 14
  },
  {
    "id": "r015",
    "name": "Chef Lee",
    "cuisine": "Korean",
    "city": "Montreal",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 8.25,
        "p": 9.25
      }
    ],
    "sort": 15
  },
  {
    "id": "r016",
    "name": "Pho Saigon Vietnam",
    "cuisine": "Vietnamese",
    "city": "Montreal",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 9,
        "p": 9.25
      }
    ],
    "sort": 16
  },
  {
    "id": "r017",
    "name": "Resto Végo",
    "cuisine": "Canadian & Comfort",
    "city": "Montreal",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 8.25,
        "p": 7
      }
    ],
    "sort": 17
  },
  {
    "id": "r018",
    "name": "Bun Mam Ninh Kieu",
    "cuisine": "Vietnamese",
    "city": "Montreal",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 9.5,
        "p": 9.25
      }
    ],
    "sort": 18
  },
  {
    "id": "r019",
    "name": "3 Brasseurs",
    "cuisine": "French",
    "city": "Montreal",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 5,
        "p": 4.75
      }
    ],
    "sort": 19
  },
  {
    "id": "r020",
    "name": "Restaurant Coréen Luna",
    "cuisine": "Korean",
    "city": "Montreal",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 8,
        "p": 7.5
      }
    ],
    "sort": 20
  },
  {
    "id": "r021",
    "name": "Tsukuyomi Ramen Crescent",
    "cuisine": "Japanese",
    "city": "Montreal",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 8,
        "p": 7.5
      }
    ],
    "sort": 21
  },
  {
    "id": "r022",
    "name": "Ramen cubby hole",
    "cuisine": "Japanese",
    "city": "Montreal",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 7,
        "p": 7
      }
    ],
    "sort": 22
  },
  {
    "id": "r023",
    "name": "Jako",
    "cuisine": "Japanese",
    "city": "Montreal",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 6,
        "p": 6.5
      }
    ],
    "sort": 23
  },
  {
    "id": "r024",
    "name": "Omnivore",
    "cuisine": "Middle Eastern",
    "city": "Montreal",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 8.75,
        "p": 8.75
      }
    ],
    "sort": 24
  },
  {
    "id": "r025",
    "name": "Nouilles Yunan",
    "cuisine": "Chinese",
    "city": "Montreal",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 6.75,
        "p": 6
      }
    ],
    "sort": 25
  },
  {
    "id": "r026",
    "name": "Icehouse",
    "cuisine": "Mexican",
    "city": "Montreal",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 8,
        "p": 7.5
      }
    ],
    "sort": 26
  },
  {
    "id": "r027",
    "name": "Chu Chai",
    "cuisine": "Thai",
    "city": "Montreal",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 9.5,
        "p": 8.5
      }
    ],
    "sort": 27
  },
  {
    "id": "r028",
    "name": "Nos The",
    "cuisine": "Brunch",
    "city": "Montreal",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 6,
        "p": 5
      }
    ],
    "sort": 28
  },
  {
    "id": "r029",
    "name": "Ginko",
    "cuisine": "Japanese",
    "city": "Montreal",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 6.5,
        "p": 5
      }
    ],
    "sort": 29
  },
  {
    "id": "r030",
    "name": "Bvrger",
    "cuisine": "Canadian & Comfort",
    "city": "Montreal",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 7.5,
        "p": 7
      }
    ],
    "sort": 30
  },
  {
    "id": "r031",
    "name": "Mimosa café",
    "cuisine": "Brunch",
    "city": "Montreal",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 6,
        "p": 5.5
      }
    ],
    "sort": 31
  },
  {
    "id": "r032",
    "name": "Yokato Yokabai",
    "cuisine": "Japanese",
    "city": "Montreal",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 4,
        "p": 5
      }
    ],
    "sort": 32
  },
  {
    "id": "r033",
    "name": "Shushu Thai",
    "cuisine": "Thai",
    "city": "Montreal",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 8,
        "p": 8.25
      }
    ],
    "sort": 33
  },
  {
    "id": "r034",
    "name": "Sunny Dinette",
    "cuisine": "Brunch",
    "city": "Montreal",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 6,
        "p": 7.75
      }
    ],
    "sort": 34
  },
  {
    "id": "r035",
    "name": "Maison v.i.p",
    "cuisine": "Chinese",
    "city": "Montreal",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 9,
        "p": 9
      }
    ],
    "sort": 35
  },
  {
    "id": "r036",
    "name": "Ches's",
    "cuisine": "Canadian & Comfort",
    "city": "Montreal",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 6.75,
        "p": 7.75
      }
    ],
    "sort": 36
  },
  {
    "id": "r037",
    "name": "Sun Sushi",
    "cuisine": "Japanese",
    "city": "Montreal",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 9,
        "p": 7.5
      }
    ],
    "sort": 37
  },
  {
    "id": "r038",
    "name": "Mallard Cottage",
    "cuisine": "Canadian & Comfort",
    "city": "Montreal",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 10,
        "p": 10
      }
    ],
    "sort": 38
  },
  {
    "id": "r039",
    "name": "Bazar Café",
    "cuisine": "Brunch",
    "city": "Montreal",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 8.5,
        "p": 8.25
      }
    ],
    "sort": 39
  },
  {
    "id": "r040",
    "name": "Queen Sheba",
    "cuisine": "Ethiopian",
    "city": "Montreal",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 2,
        "p": 1
      }
    ],
    "sort": 40
  },
  {
    "id": "r041",
    "name": "Desi Indian",
    "cuisine": "Indian",
    "city": "Montreal",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 6,
        "p": 5
      }
    ],
    "sort": 41
  },
  {
    "id": "r042",
    "name": "Shushu Ramen",
    "cuisine": "Japanese",
    "city": "Montreal",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 8,
        "p": 8
      }
    ],
    "sort": 42
  },
  {
    "id": "r043",
    "name": "Moa Moa",
    "cuisine": "Korean",
    "city": "Montreal",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 9.5,
        "p": 9.25
      }
    ],
    "sort": 43
  },
  {
    "id": "r044",
    "name": "Escondite Drummond",
    "cuisine": "Mexican",
    "city": "Montreal",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 8.75,
        "p": 8.75
      }
    ],
    "sort": 44
  },
  {
    "id": "r045",
    "name": "Kim Galbi",
    "cuisine": "Korean",
    "city": "Montreal",
    "comment": "8.5 level food, but big portions and v expensive",
    "visits": [
      {
        "label": "",
        "k": 7.5,
        "p": 7.5
      }
    ],
    "sort": 45
  },
  {
    "id": "r046",
    "name": "Au Pain Perdu",
    "cuisine": "Brunch",
    "city": "Montreal",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 8.5,
        "p": 8.25
      }
    ],
    "sort": 46
  },
  {
    "id": "r047",
    "name": "Burgundy Lion",
    "cuisine": "Canadian & Comfort",
    "city": "Montreal",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 8.75,
        "p": 5
      }
    ],
    "sort": 47
  },
  {
    "id": "r048",
    "name": "Haidalio hot pot",
    "cuisine": "Chinese",
    "city": "Montreal",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 8,
        "p": 8
      }
    ],
    "sort": 48
  },
  {
    "id": "r049",
    "name": "Bagel etc",
    "cuisine": "Brunch",
    "city": "Montreal",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 8,
        "p": 6.5
      }
    ],
    "sort": 49
  },
  {
    "id": "r050",
    "name": "Le Petit Saigon",
    "cuisine": "Vietnamese",
    "city": "Victoria, BC",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 7,
        "p": 6.75
      }
    ],
    "sort": 50
  },
  {
    "id": "r051",
    "name": "JAM Cafe",
    "cuisine": "Brunch",
    "city": "Vancouver",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 8.75,
        "p": 8.5
      }
    ],
    "sort": 51
  },
  {
    "id": "r052",
    "name": "Bvrger Fiancé",
    "cuisine": "Canadian & Comfort",
    "city": "Montreal",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 8.5,
        "p": 3.5
      }
    ],
    "sort": 52
  },
  {
    "id": "r053",
    "name": "MONO",
    "cuisine": "Korean",
    "city": "Montreal",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 8.5,
        "p": 8.75
      }
    ],
    "sort": 53
  },
  {
    "id": "r054",
    "name": "Bloom Sushi",
    "cuisine": "Japanese",
    "city": "Montreal",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 9,
        "p": 8.25
      }
    ],
    "sort": 54
  },
  {
    "id": "r055",
    "name": "Rendez-vous Bistro Indien",
    "cuisine": "Indian",
    "city": "Montreal",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 9,
        "p": 10
      }
    ],
    "sort": 55
  },
  {
    "id": "r056",
    "name": "Kiodai Izakaya",
    "cuisine": "Japanese",
    "city": "Montreal",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 5.5,
        "p": 5.5
      }
    ],
    "sort": 56
  },
  {
    "id": "r057",
    "name": "Katsuya",
    "cuisine": "Japanese",
    "city": "Montreal",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 8,
        "p": 8.25
      }
    ],
    "sort": 57
  },
  {
    "id": "r058",
    "name": "Bistro King Creole",
    "cuisine": "Caribbean",
    "city": "Montreal",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 9,
        "p": 8.75
      }
    ],
    "sort": 58
  },
  {
    "id": "r059",
    "name": "Greenspot",
    "cuisine": "Brunch",
    "city": "Montreal",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 7,
        "p": 8
      }
    ],
    "sort": 59
  },
  {
    "id": "r060",
    "name": "Trattoria Trestevere",
    "cuisine": "Italian",
    "city": "Montreal",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 7,
        "p": 7
      }
    ],
    "sort": 60
  },
  {
    "id": "r061",
    "name": "Dobe & Andy",
    "cuisine": "Chinese",
    "city": "Montreal",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 8,
        "p": 9
      }
    ],
    "sort": 61
  },
  {
    "id": "r062",
    "name": "L'Oeufrier",
    "cuisine": "Brunch",
    "city": "Montreal",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 8.5,
        "p": 6.5
      }
    ],
    "sort": 62
  },
  {
    "id": "r063",
    "name": "Lulu Épicerie",
    "cuisine": "Middle Eastern",
    "city": "Montreal",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 8.75,
        "p": 8.75
      }
    ],
    "sort": 63
  },
  {
    "id": "r064",
    "name": "Lali's",
    "cuisine": "Indian",
    "city": "Montreal",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 8.75,
        "p": 8.75
      }
    ],
    "sort": 64
  },
  {
    "id": "r065",
    "name": "Kinton Ramen Westmount",
    "cuisine": "Japanese",
    "city": "Montreal",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 8.5,
        "p": 7.5
      }
    ],
    "sort": 65
  },
  {
    "id": "r066",
    "name": "Foeigwa Brunch",
    "cuisine": "Brunch",
    "city": "Montreal",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 8.75,
        "p": 8
      }
    ],
    "sort": 66
  },
  {
    "id": "r067",
    "name": "Quoi de neuf",
    "cuisine": "Brunch",
    "city": "Montreal",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 8,
        "p": 8
      }
    ],
    "sort": 67
  },
  {
    "id": "r068",
    "name": "Louis Pizza",
    "cuisine": "Italian",
    "city": "Ottawa",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 10,
        "p": 10
      }
    ],
    "sort": 68
  },
  {
    "id": "r069",
    "name": "Zak's",
    "cuisine": "Brunch",
    "city": "Ottawa",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 9,
        "p": 7.5
      }
    ],
    "sort": 69
  },
  {
    "id": "r070",
    "name": "Garden Room",
    "cuisine": "Brunch",
    "city": "Montreal",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 8.5,
        "p": 4
      }
    ],
    "sort": 70
  },
  {
    "id": "r071",
    "name": "Shawarma Palace",
    "cuisine": "Middle Eastern",
    "city": "Ottawa",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 7,
        "p": 8
      }
    ],
    "sort": 71
  },
  {
    "id": "r072",
    "name": "Souvlaki Grec Plus",
    "cuisine": "Middle Eastern",
    "city": "Montreal",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 7.5,
        "p": 7.5
      }
    ],
    "sort": 72
  },
  {
    "id": "r073",
    "name": "Bismillah Poulet Grillé Cuisine Indienne",
    "cuisine": "Indian",
    "city": "Montreal",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 8,
        "p": 8
      }
    ],
    "sort": 73
  },
  {
    "id": "r074",
    "name": "Aqua E Farina",
    "cuisine": "Italian",
    "city": "Montreal",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 4,
        "p": 1
      }
    ],
    "sort": 74
  },
  {
    "id": "r075",
    "name": "Joyo Burger Wellington",
    "cuisine": "Canadian & Comfort",
    "city": "Montreal",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 8,
        "p": 7.5
      }
    ],
    "sort": 75
  },
  {
    "id": "r076",
    "name": "The Sparrow",
    "cuisine": "Brunch",
    "city": "Montreal",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 8,
        "p": 9.5
      }
    ],
    "sort": 76
  },
  {
    "id": "r077",
    "name": "Luyishou Fondue",
    "cuisine": "Chinese",
    "city": "Montreal",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 9,
        "p": 9.25
      }
    ],
    "sort": 77
  },
  {
    "id": "r078",
    "name": "House of Taste",
    "cuisine": "Middle Eastern",
    "city": "Montreal",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 7,
        "p": 8.25
      }
    ],
    "sort": 78
  },
  {
    "id": "r079",
    "name": "Millmans",
    "cuisine": "Brunch",
    "city": "Montreal",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 7,
        "p": 7
      }
    ],
    "sort": 79
  },
  {
    "id": "r080",
    "name": "Neotokyo",
    "cuisine": "Japanese",
    "city": "Montreal",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 8,
        "p": 8.5
      }
    ],
    "sort": 80
  },
  {
    "id": "r081",
    "name": "The Big R",
    "cuisine": "Brunch",
    "city": "Newfoundland",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 7.5,
        "p": 6
      }
    ],
    "sort": 81
  },
  {
    "id": "r082",
    "name": "Dock Marina",
    "cuisine": "Canadian & Comfort",
    "city": "Newfoundland",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 9,
        "p": 8.75
      }
    ],
    "sort": 82
  },
  {
    "id": "r083",
    "name": "Skippers",
    "cuisine": "Canadian & Comfort",
    "city": "Newfoundland",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 7,
        "p": 9
      }
    ],
    "sort": 83
  },
  {
    "id": "r084",
    "name": "Lovely Grand",
    "cuisine": "Canadian & Comfort",
    "city": "Newfoundland",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 9,
        "p": 7.5
      }
    ],
    "sort": 84
  },
  {
    "id": "r085",
    "name": "Quintal Cafe",
    "cuisine": "Brunch",
    "city": "Newfoundland",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 10,
        "p": 9.5
      }
    ],
    "sort": 85
  },
  {
    "id": "r086",
    "name": "Annie's in Twillingate",
    "cuisine": "Canadian & Comfort",
    "city": "Newfoundland",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 7,
        "p": 3
      }
    ],
    "sort": 86
  },
  {
    "id": "r087",
    "name": "Ma Poule Mouillée",
    "cuisine": "Caribbean",
    "city": "Montreal",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 8,
        "p": 9.5
      }
    ],
    "sort": 87
  },
  {
    "id": "r088",
    "name": "Kinton Ramen Square Victoria",
    "cuisine": "Japanese",
    "city": "Montreal",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 8,
        "p": 8
      }
    ],
    "sort": 88
  },
  {
    "id": "r089",
    "name": "Sammi Soup Dumpling",
    "cuisine": "Chinese",
    "city": "Montreal",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 8.5,
        "p": 7.5
      }
    ],
    "sort": 89
  },
  {
    "id": "r090",
    "name": "Tacos Lakalaka",
    "cuisine": "Mexican",
    "city": "Montreal",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 5,
        "p": 4
      }
    ],
    "sort": 90
  },
  {
    "id": "r091",
    "name": "3 Madames",
    "cuisine": "Brunch",
    "city": "Montreal",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 9,
        "p": 7.5
      }
    ],
    "sort": 91
  },
  {
    "id": "r092",
    "name": "Le Petit Dek Sen",
    "cuisine": "Thai",
    "city": "Montreal",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 8,
        "p": 8.5
      }
    ],
    "sort": 92
  },
  {
    "id": "r093",
    "name": "Siwalee",
    "cuisine": "Thai",
    "city": "Montreal",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 9,
        "p": 9
      }
    ],
    "sort": 93
  },
  {
    "id": "r094",
    "name": "Harbin St Denis",
    "cuisine": "Chinese",
    "city": "Montreal",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 6,
        "p": 7
      }
    ],
    "sort": 94
  },
  {
    "id": "r095",
    "name": "Cora",
    "cuisine": "Brunch",
    "city": "Montreal",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 8.25,
        "p": 3
      }
    ],
    "sort": 95
  },
  {
    "id": "r096",
    "name": "Pho Ahn Express",
    "cuisine": "Vietnamese",
    "city": "Montreal",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 9,
        "p": 9.25
      }
    ],
    "sort": 96
  },
  {
    "id": "r097",
    "name": "Escondite Union",
    "cuisine": "Mexican",
    "city": "Montreal",
    "comment": "",
    "visits": [
      {
        "label": "",
        "k": 8.75,
        "p": 8.75
      }
    ],
    "sort": 97
  }
];
